### ISSUE TITLE
 🤞 Android D6Flasher Alternative for PC 

### ISSUE THREAD

**Issue by sebi5361** [atc1441/D6-arduino-nRF5#2]
Dear Aaron, thank you for this excellent work 🤗
Do you know is there is an alternative to D6Flasher that would run on a PC?
(I don't have an Android device with bluetooth.)

**Comment by atc1441** [comment]
Hi again, just for complementation i will answer here again,
yes you can use the nrfutil that is included in the repo, and flash over serial with it, on @fanoush github is the manual and also a version for python. But an ble version is not known for me. Maybe that is a good project to start next.

**Comment by sebi5361** [comment]
Thx!
