### ISSUE TITLE
BLE-DFU works for Micropython, but not for Arduino, any hints?

### ISSUE THREAD

**Issue by gerardwr** [atc1441/D6-arduino-nRF5#4]
Hi,

Like your videos about D6Flasher and DaFlasher, thanks for sharing!

I could use your help in flashing Arduino firmware in my Nrf52832 module (E104-BT5032A nRF52832). After I want to shift to an Nrf52832 Smartwatch.

Flashing bootloader and softdevice via OpenOcd/ST-Link works OK and:
- flashing Micropython@fanoush via NrfConnect works OK (details below).
- flashing Micropython@fanoush via your D6Flasher App works OK too.

But uploading an Arduino hex file compiled for NRF52832 using NrfConnect or D6Flasher App fails every time. NrfConnect disconnects after some seconds without uploading.

I guess the bootloader+softdevice that works for micropython is not right for Arduino.

I have been reading for days and experimenting with different bootloaders, different softdevices, but without success. The BLE upload always fails.

Would be great if  you could point me in the right direction, I’m not sure where my mistake is.

Greetings.

DETAILED INFO
=============
- OpenOCD command on Apple iMac:
`iMac19-9:espruino gerard$ openocd -f interface/stlink-v2.cfg  -f target/nrf52.cfg -d2 -c init -c "reset init" -c halt -c "nrf5 mass_erase" -c "program s132_nrf52_6.1.1_softdevice.hex verify" -c "program dsd6_nrf52832_bootloader-0.2.11-3-gfb847b9-dirty-nosd.bin verify 0x78000" -c "flash write_bank 1 dsd6-uicr.bin" -c "flash banks" -c reset -c exit`

- AdaDFU device appears in NrfConnect App, after connecting, I can upload the micropython binary
- the micropython binary works fine using Webbluetooth in Chrome browser.

- AdaDFU device appears in D6Flasher App, after connecting, I can upload the micropython binary
- the micropython binary works fine using Webbluetooth in Chrome browser.

**Comment by atc1441** [comment]
Hi sorry for answering late, 

the problem you have is the SoftDevice version,

you need the version nr. 2.0.1 for this Arduino library. also the Bootloader needs to be compiled for that version.

you are using 6.1.1

**Comment by gerardwr** [comment]
Hi,

Thanks for your reply.

Have tried a lot of BL and SD combinations without success, so some focus is great.

I will try flashing a combination of an SD version 2.0.1 and matching bootloader.

Will report back how it goes.

**Comment by atc1441** [comment]
In general you could use the portable arduino variant and flash the P8 "Stock" firmware. It containes the sd2 and a bootloader that trys to write to the display but it should work even when no display is connected. After that you can flash a simple sketch to it with the ability to go into bootloader mode. And from there you can flash anything else OTA or via the Arduino swd upload

**Comment by gerardwr** [comment]
That REALLY helps, thanks! I flashed the P8-stock firmware, and can now upload Arduino sketches using the NrfConnect App. See details here below.

Will try D6Flasher/DaFlasher next.

Greetings!!

DETAILED DESCRIPTION
==================
I downloaded your portable Arduino variant from http://atcnetz.de/downloads/D6Arduino.rar
, but it's for Windows and I'm on Mac, so I could not run it.

But I found:
- in your "platform.txt" file the way you flash the P8-Stock firmware.
- the "Softdevices" directory contains the required firmware files

So I used this openocd command:
```
pi@raspberrypi3:~/Mydata/Nrf52832/firstexperiments $ sudo openocd -f
interface/raspberrypi2-native.cfg -c "transport select swd" -f
target/nrf52.cfg -d2 -c init -c "reset init" -c halt -c "nrf5
mass_erase" -c "program dsd6-flashP8.bin verify" -c "flash write_bank 1
dsd6-uicr-flashP8.bin" -c "flash banks" -c "reset run" -c exit
```
After flashing, the device ATCdfu appeared in the NrfConnect App.
![Screenshot_20200606-215112](https://user-images.githubusercontent.com/10114857/83953814-ecf55e00-a843-11ea-9145-8b1711f02b32.png)

After connecting to the ActDfu device I could upload a compiled Arduino .ZIP sketch without any problem.
![Screenshot_20200606-215208](https://user-images.githubusercontent.com/10114857/83953851-45c4f680-a844-11ea-99cd-8beb05b68d89.png)

The sketch provides a (fake) BLE HeartRate service, my device is listed in NrfConnect App.
![Screenshot_20200606-215257](https://user-images.githubusercontent.com/10114857/83953863-5e351100-a844-11ea-9e7b-928c28630ca1.png)

My Heartrate device is recognised by the NrfToolbox App.
![Screenshot_20200606-222728](https://user-images.githubusercontent.com/10114857/83953951-211d4e80-a845-11ea-8414-442da5f3fdb6.png)

So now I can use Arduino sketches using BLE, great!

**Comment by atc1441** [comment]
Nice to see it works as you want :)
And thank you for your very detailed description.

I am closing it now

**Comment by gerardwr** [comment]
Just for completeness:

Instead of using NrfConnect DFU to upload the Arduino sketch you can also combine flashing the P8-stock firmware and the Arduino .hex file using OpenOcd with this command:
```
pi@raspberrypi3:~/Mydata/Nrf52832/firstexperiments $ sudo openocd -f
interface/raspberrypi2-native.cfg -c "transport select swd" -f
target/nrf52.cfg -d2 -c init -c "reset init" -c halt -c "nrf5
mass_erase" -c "program dsd6-flashP8.bin verify" -c "program
HeartRateBLE.ino.hex" -c "flash write_bank 1 dsd6-uicr-flashP8.bin" -c
"flash banks" -c "reset run" -c exit
```
